### ISSUE TITLE
Image 404 Error

### ISSUE THREAD

**Issue by huan** [wechaty/bot5.club#46]
https://www.bot5.club/events/seminar-minutes-7/

@darkli We need to test the blog post at the local environment in order to make everything is ok before we send the PR to publish on our BOT5 club website.

Please go to the online page and fix the 404 errors, thanks!

**Comment by huan** [comment]
@lijiarui As the approver and the merger for the PR, I believe we need to double-check the result so that we can find the problem earlier.

I'm considering to add some memos on the chairs' manual, do you think it's necessary?

**Comment by huan** [comment]
![image](https://user-images.githubusercontent.com/1361891/64103427-d269f200-cda4-11e9-83fd-cbea12809025.png)

Please also notice that the `teaser` has also 404-ed. @darkli

**Comment by huan** [comment]
There still a 404 error with the latest version of the post.

```markdown
2 Bot Market Place — 可重用能力平台
![李卓桓]({{ '/assets/2019/seminar-7/talk-nanopi-lianghaoran.jpg' | relative_url }})

李卓桓，Github 6000 Star 的微信个人号SDK开源项目 Wechaty 作者，Conversational AI 布道者。曾任水木清华BBS站长，优酷网首席科学家。清华本科，中欧EMBA，北邮博士在读。
```

**Comment by lijiarui** [comment]
@huan Agree with you. I should double-check before the merge.

And, adding some memos on the chairs' manual is really necessary.

**Comment by huan** [comment]
The 404 error was fixed. However, there's no photo of my talk in this seminar. 

Sad. @darkli
