### ISSUE TITLE
chair manual should update

### ISSUE THREAD

**Issue by qhduan** [wechaty/bot5.club#68]
- [ ] 优先按照已经登记的talks询问下一次talk
- [ ] 询问其他人是否可以下一次talk
- [ ] 确认会议地点，如主席自己没有地点，考虑咨询上届主席，主办方（句子互动）
- [ ] 确认小吃赞助（有、没有、谁）
- [ ] 尽早发布群内通知

**Comment by huan** [comment]
Good job! @windmemory
